### ISSUE TITLE
current todo list

### ISSUE THREAD

**Issue by ninabreznik** [playproject-io/datdot-service#15]
- [ ] gracefully closing hyperbeams
- [ ] proof of performance - new logic
- [ ] account creation - refactoring old Mauve's logic
