### ISSUE TITLE
flows: hoster setup + proof of storage

### ISSUE THREAD

**Issue by ninabreznik** [playproject-io/datdot-service#16]
## `@todo`
* [ ] improve hosting setup for encoder
* [ ] improve hosting setup for hoster
* [ ] improve hosting setup for attestor
* [ ] improve hosting setup for chain
* [ ] improve proof of storage for hoster
* [ ] improve proof of storage for attester
* [ ] improve proof of storage for chain
* [ ] add accounting logic to hosting setup
* [ ] add payment logic to proof of storage

---

![](http://imgur.com/uQnecyal.png)
![](http://imgur.com/KnFQXohl.png)

**Comment by ninabreznik** [comment]
# improve hosting setup for encoder

**Comment by ninabreznik** [comment]
# improve hosting setup for hoster

**Comment by ninabreznik** [comment]
# improve hosting setup for attestor

**Comment by ninabreznik** [comment]
# improve hosting setup for chain

**Comment by ninabreznik** [comment]
# improve proof of storage for hoster

**Comment by ninabreznik** [comment]
# improve proof of storage for attestor

**Comment by ninabreznik** [comment]
# improve proof of storage for chain

**Comment by ninabreznik** [comment]
# add accounting logic to hosting setup

**Comment by ninabreznik** [comment]
# add payment logic to proof of storage
