### ISSUE TITLE
standard for discovering related hypercores

### ISSUE THREAD

**Issue by serapath** [playproject-io/datdot-service#7]
## `@todo`
* [ ] talk to community/ecosystem about a standard for discovering related hypercores
* [ ] write proposal for standard, implement a demo and get feedback from community/ecosystem
* [ ] support the standard in `datdot`

---

**Comment by ninabreznik** [comment]
What time are the calls? I want to add it to my Calendar

**Comment by serapath** [comment]
i actually don't know when the consortium call is, only the date. if you learn about the time, please ping :-)

**Comment by serapath** [comment]
# Data Structures which use `hypercore`

**issue:** a `generic seeding service` receives a `"dat address"` and doesn't know which kind of data structure is behind that address and needs to know all related `hypercores` and how to retrieve them and a standard way of making them available to anyone who wants to use the data and data structure behind that "dat address"

### HYPERCORE
* is the basic type of `feed`
* has only one main feed associated with a corresponding `"dat address"`
* by default is not aware of any related feeds it might reference via messages

### HYPERTRIE
* is a special type of `feed`
* has only one main feed associated with a corresponding `"dat address"`
* by default is not aware of any related feeds it might reference via messages

### HYPERDRIVE
* has main `metafeed` associated with a corresponding `"dat address"`
  * in `message 0` references a related `contentfeed`
  * it otherwise is a **hypertrie**
    * which gives all related `feeds` via `trie.list(‘mounts’, { hidden: true }, cb)`

###

**Comment by serapath** [comment]
# kappa-core / multifeed / multiplex

## multifeed - mux
* [ ] https://github.com/kappa-db/multifeed/blob/master/mux.js

## multifeed - index
* [x] https://github.com/kappa-db/multifeed/blob/master/index.js#L258

### LOCAL PEER STORAGE
```js
self._streams = [] // all peers in the form of `mux` objects
```

### LOCAL FEED STORAGE
```js
self._feeds = {
  [feedkey1]: feed1,
  [feedkey2]: feed2,
  [feedkey3]: feed3,
}
```

### on READY offers all it's FEED KEYS to PEERS
```js
mux.ready(function () {
  var keys = values(self._feeds).map(function (feed) { return feed.key.toString('hex') })
  mux.offerFeeds(keys)
})
```

### stores locally and offers new FEED to PEERS
```js
Multifeed.prototype._addFeed = function (feed, name) {
  self._feeds[name] = feed
  self._feedKeyToFeed[feed.key.toString('hex')] = feed
  feed.setMaxListeners(Infinity)
  self.emit('feed', feed, name)

  // forward live feed announcements
  if (!self._streams.length) return // no-op if no live-connections
  var hexKey = feed.key.toString('hex')
  // Tell each remote that we have a new key available unless it's already being replicated
  self._streams.forEach(function (mux) {
    if (!~mux.knownFeeds().indexOf(hexKey)) mux.offerFeeds([hexKey])
  })
}
```

### add new peer (`mux`) 
```js
Multifeed.prototype.replicate = function (isInitiator, opts) {
  // All multifeeds get a random or passed in `_id`
  // When "ready" they make a feed using a default or passed encryptionKey and set it as `_root` feed

  // MAKE SESSION
  var mux = multiplexer(isInitiator, self._root.key, Object.assign({}, opts, {_id: this._id}))
  /* on ready */ self._streams.push(mux)

  // KEY EXCHANGE listener
  mux.on('manifest', function onManifest(m) { mux.requestFeeds(m.keys) }

  mux.on('replicate', function onReplicate(keys, done) { // REPLICATION REQUEST?
    await addMissingKeys(keys)
    // 1. make sure all keys are proper feedkeys
    // 2. check non of the given feeds already exist
    // for all new keys:
    //   1. make a storage with name "myKey" is "self._feeds.length"
    //   2. make new hypercore for the new feed
    //   3. `self._addFeed(feed, myKey)

    // => looks up all existing feeds based on given keys
    // => calls `mux` callback to replicate those feeds

    done(feed) // replicates
  })

  return mux.stream
}
```

**Comment by serapath** [comment]
**BACKGROUND**
1. currently every protocol/structure has a custom way to communicate it's related feeds
    * e.g. **hyperdrive** has `metafeed` with a first message to link `contentfeed` and further messages form a hypertrie to link `mounts` all signed by author
        * => only the author can spam and needs to be trusted to not do that and to protect against it i can just reject feed updates
    * e.g. **cabal** clients just send their feedkeys to new clients for collection via a MANIFEST extension message
        * => anyone can spam with new feeds and to protect against spam subjective whitelisting or blacklisting of feeds can be used

2. It requires a user to use the right client when joining a swarmkey to request feeds
3. If the user copy/pasted the "dat address" into a `"dat cloud service"` it would now be up to the cloud to request related

**PROPOSAL** (for a DEP about `RELATED FEEDS`)
1. a special EXTENSION MESSAGE with the `main feedkey`
2. receiving peers respond with their `manifestkey`
    * if there is no single author (e.g. multifeed), many `manifestkeys` exist
3. the manifestfeed(s) contain a list of related feedkeys to the `main feedkey`
    * each entry specifies the swarmkey for that related feed and whether its relation is
        * a `part` (e.g. contenfeed)
        * or a `link` (e.g. mounts)
        * and maybe an `origin` to cite reason/proof why a feed is related
          * (e.g. for a contentfeedkey, that could be the hyperdrive metakey + chunk 0 of the real author)

**Comment by okdistribute** [comment]
@serapath it's multifeed that's doing that, not cabal, just to be clear :)

**Comment by serapath** [comment]
@okdistribute when checking i found `cabal-core` to use `kappa-core` and `kappa-core` to use `multifeed`, so it felt like underneath, that's whats happening on the level of exchanging hypercores.
can you recommend me where or what i should be looking at additionally?

**Comment by okdistribute** [comment]
Sorry I think I wasn't clear, the datastructure that handles the feeds in cabal is multifeed, and in hyperdrive, it's corestore. So any app built on multifeed or corestore would work with datdot, if you target those datastructures rather than a particular application like hyperdrive or cabal
