### ISSUE TITLE
implement encoding-hosting-challenge flow and add a test scenario

### ISSUE THREAD

**Issue by serapath** [playproject-io/datdot-service#8]
## `@todo`
* [ ] [`datdot#24` encoding compatible hypercores](https://github.com/playproject-io/datdot/issues/24)
* [ ] check current encoding-hosting scenario code in `datdot-service` repo
* [ ] integrating existing new code into it
* [ ] refactor code and modules to use dat-SDK
* [ ] adding missing parts to it (what are they?)
* [ ] add manual handling of different data structures

---
## `later`
* [ ] [`datdot-service#7` standard for discovering related hypercores](https://github.com/playproject-io/datdot-service/issues/7)

---
